/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import com.darkprograms.speech.translator.GoogleTranslate;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame implements ActionListener {

    private ArrayList<Word> words_list;
    private DefaultListModel<String> list_mod;

    /**
     * Creates new form Vit_Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        words_list = readWordsFromDB();
        list_mod = new DefaultListModel();
        listOfWords.setModel(list_mod);
        addElement();
        txtWordex.setContentType("text/html");
        addActionListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        listOfWords = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        speakBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        scrollWordex = new javax.swing.JScrollPane();
        txtWordex = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        CBBFrom = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtFrom = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTo = new javax.swing.JTextArea();
        CBBTo = new javax.swing.JComboBox<>();
        translateBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TỪ ĐIỂN OFFLINE");
        setBackground(new java.awt.Color(102, 102, 255));
        setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" DEMO Từ điển ");

        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel1.setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tìm kiếm");

        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFindKeyTyped(evt);
            }
        });

        listOfWords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listOfWordsMouseClicked(evt);
            }
        });
        scroll.setViewportView(listOfWords);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nghĩa của từ");

        speakBtn.setText("Phát âm");

        addBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addBtn.setText("Thêm");

        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteBtn.setText("Xóa");

        editBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editBtn.setText("Sửa");

        scrollWordex.setViewportView(txtWordex);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtFind, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(speakBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollWordex, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(speakBtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtFind)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollWordex)
                    .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(deleteBtn)
                    .addComponent(editBtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tra nghĩa của từ", jPanel1);

        jPanel2.setFocusTraversalPolicyProvider(true);

        CBBFrom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CBBFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng Việt", "Tiếng Anh", "Tiếng Trung" }));

        txtFrom.setColumns(20);
        txtFrom.setRows(5);
        jScrollPane3.setViewportView(txtFrom);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Đoạn văn cần dịch");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Đoạn văn sau khi dịch");

        txtTo.setColumns(20);
        txtTo.setRows(5);
        jScrollPane4.setViewportView(txtTo);

        CBBTo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CBBTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng Việt", "Tiếng Anh", "Tiếng Trung" }));

        translateBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        translateBtn.setText("Dịch");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(CBBTo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CBBFrom, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(translateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CBBFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CBBTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(translateBtn)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dịch đoạn văn", jPanel2);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Thoát");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void listOfWordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listOfWordsMouseClicked
        txtWordex.setText(findWordEx(listOfWords.getSelectedValue()));    }//GEN-LAST:event_listOfWordsMouseClicked

    private void txtFindKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyTyped
        // TODO add your handling code here:
        String str = txtFind.getText().trim();
        str += evt.getKeyChar();
        str = str.toLowerCase().trim();
        String s;

        for (int i = 0; i < list_mod.size(); i++) {
            s = list_mod.getElementAt(i);
            s = s.toLowerCase();
            if (s.startsWith(str)) {
                listOfWords.setSelectedIndex(i);
                txtWordex.setText(findWordEx(listOfWords.getSelectedValue()));
                JScrollBar sc_bar = scroll.getVerticalScrollBar();
                sc_bar.setValue(i * 20);
                return;
            }
        }
    }//GEN-LAST:event_txtFindKeyTyped
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBBFrom;
    private javax.swing.JComboBox<String> CBBTo;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listOfWords;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JScrollPane scrollWordex;
    private javax.swing.JButton speakBtn;
    private javax.swing.JButton translateBtn;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextArea txtFrom;
    private javax.swing.JTextArea txtTo;
    private javax.swing.JTextPane txtWordex;
    // End of variables declaration//GEN-END:variables

    public ArrayList<Word> readWordsFromDB() {
        ArrayList<Word> words_list = new ArrayList<Word>();
        Connection connection = null;
        Statement statement = null;

        try {
            connection = DriverManager.getConnection("jdbc:sqlite:dict_hh.db");
            String sql = "SELECT * FROM av";
            statement = connection.createStatement();
            ResultSet resultset = statement.executeQuery(sql);

            while (resultset.next()) {
                String word_target = resultset.getString("word");
                //String word_ex = resultset.getString("description");
                //String word_pronounce = resultset.getString("pronounce");
                //String word_explain = word_pronounce + "\n" + word_ex;
                String word_explain = resultset.getString("html");

                words_list.add(new Word(word_target, "<html>" + word_explain + "</html>"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

        return words_list;
    }

    public void addElement() {
        for (Word word : words_list) {
            list_mod.addElement(word.getWord_target());
        }
    }

    public String findWordEx(String wtg) {
        for (Word word : words_list) {
            if (word.getWord_target().equals(wtg)) {
                return word.getWord_explain();
            }
        }
        return null;
    }

    public void addActionListener() {
        translateBtn.addActionListener(this);
        speakBtn.addActionListener(this);
        addBtn.addActionListener(this);
        deleteBtn.addActionListener(this);
        editBtn.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Object obj = e.getSource();
        if (obj.equals(translateBtn)) {
            try {
                translate();
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (obj.equals(speakBtn)) {
            speak();
        } else if (obj.equals(addBtn)) {
            add();
        } else if (obj.equals(editBtn)) {
            edit();
        } else if (obj.equals(deleteBtn)) {
            delete();
        }
    }
    
    public void delete() {
        if (listOfWords.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn một từ để xóa!");
        } else {
            Object[] options = { "Có", "Không" };
            int returnValue = JOptionPane.showOptionDialog(rootPane, 
                    "Bạn có chắc muốn xóa từ này không?", "Cảnh báo",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,
                    null, options, options[0]);
            if (returnValue == JOptionPane.YES_OPTION) {
                Word wordToDelete = new Word(listOfWords.getSelectedValue(), "");
                wordToDelete.setWord_explain(findWordEx(wordToDelete.getWord_target()));
                
                Connection connection = null;
                PreparedStatement deleteStatement = null;
                PreparedStatement editStatement = null;
                try {
                    connection = DriverManager.getConnection("jdbc:sqlite:dict_hh.db");
                    String deleteSQL = "DELETE FROM av WHERE id = ?";
                    deleteStatement = connection.prepareStatement(deleteSQL);
                    deleteStatement.setInt(1, listOfWords.getSelectedIndex() + 1);
                    deleteStatement.executeUpdate();
                    
                    for (int i = listOfWords.getSelectedIndex() + 2; i <= list_mod.getSize(); i++) {
                        String updateSQLid = "UPDATE av SET id = id - 1 WHERE id = ?";
                        editStatement = connection.prepareStatement(updateSQLid);
                        editStatement.setInt(1, i);
                        editStatement.executeUpdate();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                words_list.remove(wordToDelete);
                list_mod.removeElement(wordToDelete.getWord_target());
                listOfWords.setModel(list_mod);
            }
        }
    }
    
    public void add() {
        String inputWordTarget = (String) JOptionPane.showInputDialog(rootPane, 
                "Nhập từ bạn muốn thêm", "Thêm từ",
                JOptionPane.PLAIN_MESSAGE);
        boolean isWordExists = false;
        for (Word word : words_list) {
            if (word.getWord_target().equals(inputWordTarget)) {
                isWordExists = true;
            }
        }
        if (isWordExists) {
            JOptionPane.showMessageDialog(rootPane, 
                "Từ này đã tồn tại trong từ điển!", "Lỗi",
                JOptionPane.ERROR_MESSAGE);
        } else {
            String inputWordExplain = (String) JOptionPane.showInputDialog(rootPane, 
                "Nhập giải nghĩa của từ", "Thêm giải nghĩa",
                JOptionPane.PLAIN_MESSAGE);
            Connection connection = null;
            PreparedStatement statement = null;
            try {
                connection = DriverManager.getConnection("jdbc:sqlite:dict_hh.db");
                String insertSQL = "INSERT INTO av (id, word, html, description) VALUES (?, ?, ?, ?)";
                statement = connection.prepareStatement(insertSQL);
                statement.setInt(1, list_mod.size() + 1);
                statement.setString(2, inputWordTarget);
                String htmlEx = "<h1>" + inputWordTarget + "</h1>"
                        + "<ul><li>" + inputWordExplain + "</li></ul>";
                statement.setString(3, htmlEx);
                statement.setString(4, inputWordExplain);
                statement.executeUpdate();
                inputWordExplain = htmlEx;
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            Word wordToAdd = new Word(inputWordTarget, "<html>" + inputWordExplain + "</html>");
            words_list.add(wordToAdd);
            list_mod.addElement(wordToAdd.getWord_target());
            listOfWords.setModel(list_mod);
        }
    }
    
    public void edit() {
        if (listOfWords.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn một từ để sửa!");
        } else {
            Object[] options = { "Từ", "Nghĩa"};
            int returnValue = JOptionPane.showOptionDialog(rootPane, 
                    "Bạn muốn sửa từ hay sửa nghĩa?", "",
                    JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                    null, options, options[0]);
            if (returnValue == JOptionPane.YES_OPTION) {
                String editWordTarget = (String) JOptionPane.showInputDialog(rootPane, 
                "Bạn muốn sửa thành từ gì?", "Sửa từ",
                JOptionPane.PLAIN_MESSAGE);
                boolean isWordExists = false;
                for (Word word : words_list) {
                    if (word.getWord_target().equals(editWordTarget)) {
                        isWordExists = true;
                    }
                }
                if (isWordExists) {
                    JOptionPane.showMessageDialog(rootPane, 
                        "Từ này đã tồn tại trong từ điển!", "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
                } else {
                    Connection connection = null;
                    PreparedStatement wordStatement = null;
                    Statement readDesStatement = null;
                    PreparedStatement exStatement = null;
                    int id = listOfWords.getSelectedIndex() + 1;
                    try {
                        connection = DriverManager.getConnection("jdbc:sqlite:dict_hh.db");
                        String updateSQL = "UPDATE av SET word = ? WHERE id = ?";
                        wordStatement = connection.prepareStatement(updateSQL);
                        wordStatement.setString(1, editWordTarget);
                        wordStatement.setInt(2, id);
                        wordStatement.executeUpdate();
                        
                        String readSQL = "SELECT description FROM av WHERE id = " + id;
                        readDesStatement = connection.createStatement();
                        ResultSet resultset = readDesStatement.executeQuery(readSQL);

                        String description = resultset.getString("description");
                        
                        updateSQL = "UPDATE av SET html = ? WHERE id = ?";
                        exStatement = connection.prepareStatement(updateSQL);
                        String htmlEx = "<h1>" + editWordTarget + "</h1>"
                        + "<ul><li>" + description + "</li></ul>";
                        exStatement.setString(1, htmlEx);
                        exStatement.setInt(2, id);
                        exStatement.executeUpdate();
                        
                        words_list.get(listOfWords.getSelectedIndex())
                            .setWord_explain(htmlEx);
                    } catch (SQLException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    words_list.get(listOfWords.getSelectedIndex())
                            .setWord_target(editWordTarget);
                    list_mod.setElementAt(editWordTarget, listOfWords.getSelectedIndex());
                    listOfWords.setModel(list_mod);
                }
            }
            if (returnValue == JOptionPane.NO_OPTION) {
                String editWordExplain = (String) JOptionPane.showInputDialog(rootPane, 
                        "Bạn muốn sửa giải nghĩa như thế nào?", "Sửa giải nghĩa",
                        JOptionPane.PLAIN_MESSAGE);
                Connection connection = null;
                PreparedStatement htmlStatement = null;
                PreparedStatement desStatement = null;
                try {
                    connection = DriverManager.getConnection("jdbc:sqlite:dict_hh.db");

                    String updateSQL = "UPDATE av SET html = ? WHERE id = ?";
                    htmlStatement = connection.prepareStatement(updateSQL);
                    String htmlEx = "<h1>" + listOfWords.getSelectedValue() + "</h1>"
                            + "<ul><li>" + editWordExplain + "</li></ul>";
                    htmlStatement.setString(1, htmlEx);
                    htmlStatement.setInt(2, list_mod.size() + 1);
                    htmlStatement.executeUpdate();

                    updateSQL = "UPDATE av SET description = ? WHERE id = ?";
                    desStatement = connection.prepareStatement(updateSQL);
                    desStatement.setString(1, editWordExplain);
                    desStatement.setInt(2, list_mod.size() + 1);
                    desStatement.executeUpdate();
                    words_list.get(listOfWords.getSelectedIndex())
                        .setWord_explain(htmlEx);
                } catch (SQLException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    public void speak() {
        System.setProperty("freetts.voices", "com.sun.speech.freetts.en.us.cmu_us_kal.KevinVoiceDirectory");
        Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice("kevin16");
        voice.allocate();
        voice.speak(listOfWords.getSelectedValue());
    }

    public void translate() throws IOException {
        txtTo.setText(GoogleTranslate.translate(find6391Codes(CBBFrom.getSelectedItem().toString()),
                find6391Codes(CBBTo.getSelectedItem().toString()), txtFrom.getText()));

    }

    public String find6391Codes(String language) {
        switch (language) {
            case "Tiếng Việt":
                return "vi";
            case "Tiếng Anh":
                return "en";
            case "Tiếng Trung":
                return "zh";
            default:
                break;
        }
        return null;
    }

}
